### PR TITLE
Uploading All Assignments

### PR DESCRIPTION
**Pull request by katattakacs**
Hi!
I think I did this right, and I think I kind of get it. But let me know if I did it wrong...or it's not right.
Thank you!
Katie

### CODE REVIEW

**Comment by katattakacs** [comment]
Let's see if this did the trick...

**Comment by katattakacs** [comment]
I'm trying to upload my Final, and for some reason, I feel like it's still not uploading to git hub...so, let's see if something happens if I let it chill a minute....

**Comment by katattakacs** [comment]
Here's the READ.ME for my final. Hopefully.

**Comment by katattakacs** [comment]
https://github.com/katattakacs/SDSFinal.git

not sure this will work, but lets try this...

**Comment by katattakacs** [comment]
https://github.com/katattakacs/SDSFinal.git

**Comment by bitchwhocodes** [comment]
nicely done ! Got it and merging

**Comment by katattakacs** [comment]
Yes!!!
I literally have no idea why that was a feat.

**Pull request merged**
